In [30]:

import numpy as np
import scipy
from scipy.misc import imread, imsave, imresize
import skimage
from skimage import data
from matplotlib import pyplot as plt
from skimage.util.shape import view_as_blocks
from skimage.transform import rescale, resize, downscale_local_mean
from skimage import feature
from skimage.transform import warp, AffineTransform
from skimage import io
%matplotlib inline
from PIL import Image


def myGrad_Y(sub_Block,direction,(M,N)):
    
   #  row =  sub_Block[nr of block][nr row, nr of col]   
    print sub_Block[2,0]
    
#     print sub_Block[15][0,2]
#     sub_Block[15][0,1]
#     sub_Block[15][0,3]

    grad_sub_Block=[]   
    
    for col in range(0,M):
        print '******* i:  %d  : ' % i
        grad_sub_Block.append([])
        for row in range(1,N-1):
            grad_sub_Block[i].append(sub_Block[row-1,col]-sub_Block[col,row+1])    
            
        print  grad_sub_Block[i]
    return  grad_sub_Block   

# sub_Block = [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]
sub_Block= np.arange(16).reshape((4, 4))

print  sub_Block

sub_Block=np.lib.pad(sub_Block, (1,1), 'constant', constant_values=(0))

print  'padded'
print  sub_Block




grad_sub_Block=[]   
    
for col in range(0,4+2):
    print '*******col :  %d  : ' % col
    grad_sub_Block.append([])
    for row in range(0,4+2):
        print sub_Block[row,col-1], sub_Block [row,col] ,sub_Block [row,col+1] 
        
#                 grad_sub_Block[i].append(sub_Block[row-1,col]-sub_Block[col,row+1])    
            
#         print  grad_sub_Block[i]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
padded
[[ 0  0  0  0  0  0]
 [ 0  0  1  2  3  0]
 [ 0  4  5  6  7  0]
 [ 0  8  9 10 11  0]
 [ 0 12 13 14 15  0]
 [ 0  0  0  0  0  0]]
*******col :  0  : 
0 0 0
0 0 0
0 0 4
0 0 8
0 0 12
0 0 0
*******col :  1  : 
0 0 0
0 0 1
0 4 5
0 8 9
0 12 13
0 0 0
*******col :  2  : 
0 0 0
0 1 2
4 5 6
8 9 10
12 13 14
0 0 0
*******col :  3  : 
0 0 0
1 2 3
5 6 7
9 10 11
13 14 15
0 0 0
*******col :  4  : 
0 0 0
2 3 0
6 7 0
10 11 0
14 15 0
0 0 0
*******col :  5  : 
0 0

IndexError: index 6 is out of bounds for axis 1 with size 6